### ISSUE TITLE
Deliverable: New GitHub repository for the Datatracker correctly populated with migrated data from Trac and Subversion

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#1]

**Comment by ronaldtse** [comment]
Trac tickets and SVN data available now at:
* `ietfdb` (datatracker): https://github.com/ietf-svn-conversion/ietfdb

@rjsparks this repo is ready for review.

**Comment by rjsparks** [comment]
The default branch is odd - why is it not main?

**Comment by rjsparks** [comment]
It's surprising that it only shows three contributors - the mapping should have indicated quite a few more?

**Comment by rjsparks** [comment]
What is the n/a label? It doesn't seem useful.

**Comment by rjsparks** [comment]
I have a mild concern about almost all commits showing
![image](https://user-images.githubusercontent.com/10996692/143937817-eb79b761-6496-48d8-944f-cc493bf7d100.png)

**Comment by rjsparks** [comment]
I am curious about the way github creates the zip and tarballs at places like: https://github.com/ietf-svn-conversion/ietfdb/releases/tag/personal%2Frjs%2F7.40.1.dev0-root - are those generated on demand? If not, we're probably causing _many_ of them to be created, and very few will be useful.

Also /personal/rjs/7.40.1.dev0-root does not exist in svn - only /persona/rjs/7.40.1.dev0. Why is -root necessary here?

**Comment by HassanAkbar** [comment]
> The default branch is odd - why is it not main?

I will change that to `main`.

> It's surprising that it only shows three contributors - the mapping should have indicated quite a few more?

Currently we are only testing so that is why we didn't map all the users so that they don't get notifications/contributions. That's why there are only 3 test contributors added for now.

> What is the n/a label? It doesn't seem useful.

It is currently in the trac database but we can remove it if its useless.

**Comment by rjsparks** [comment]
Thanks Hassan - responses about the default branch and the contributors understood.

re: n/a - there is an issue with the loss of context when moving to labels the way we're doing it now - in trac these are always appear with "Priority:" printed right before them wherever they are shown. It's easy to infer that the other values are priorities without that context, but n/a in isolation will only be confusing. In trac, it means the priority has not been set, so we should either
1) Just not map n/a to a label (my preference)
2) map it to "no priority"

An on mapping users: I suspect that in not mapping all users, we're really only protecting them from one notification (about subscription) per repository? That's all I received fwiw. It's ok to wait to map the rest until later still.

**Comment by rjsparks** [comment]
It occurs to me that we may be mapping n/a out of more than just Priority - this may be what trac is providing when a ticket submitter didn't provide any data for other fields, such as Component. I think all fields having an n/a value should receive the same treatment as above, with the preference for mapping to no label, with a fallback of no {whatever the field was}.

**Comment by HassanAkbar** [comment]
> Thanks Hassan - responses about the default branch and the contributors understood.
> 
> re: n/a - there is an issue with the loss of context when moving to labels the way we're doing it now - in trac these are always appear with "Priority:" printed right before them wherever they are shown. It's easy to infer that the other values are priorities without that context, but n/a in isolation will only be confusing. In trac, it means the priority has not been set, so we should either
> 
> 1. Just not map n/a to a label (my preference)
> 2. map it to "no priority"

@rjsparks Got it. We will remove mapping to `n/a` labels.

> 
> An on mapping users: I suspect that in not mapping all users, we're really only protecting them from one notification (about subscription) per repository? That's all I received fwiw. It's ok to wait to map the rest until later still.

Yes, you are right about notifications.
Sounds good 👍

>It occurs to me that we may be mapping n/a out of more than just Priority - this may be what trac is providing when a ticket submitter didn't provide any data for other fields, such as Component. I think all fields having an n/a value should receive the same treatment as above, with the preference for mapping to no label, with a fallback of no {whatever the field was}.

Yes, that completely makes sense. We will not map `n/a` value to any field to keep the same behavior across all fields.

**Comment by HassanAkbar** [comment]
> I have a mild concern about almost all commits showing ![image](https://user-images.githubusercontent.com/10996692/143937817-eb79b761-6496-48d8-944f-cc493bf7d100.png)

@rjsparks Let me get back to you on this.

>I am curious about the way github creates the zip and tarballs at places like: https://github.com/ietf-svn-conversion/ietfdb/releases/tag/personal%2Frjs%2F7.40.1.dev0-root - are those generated on demand? If not, we're probably causing _many_ of them to be created, and very few will be useful.

The `Source code (zip)` and `Source code (tar.gz)` folders are auto-generated by Github on `Tag` creation.

>Also /personal/rjs/7.40.1.dev0-root does not exist in svn - only /persona/rjs/7.40.1.dev0. Why is -root necessary here?

You are right. Let me get back to you on this.

**Comment by ronaldtse** [comment]
> The default branch is odd - why is it not main?

When a repository is empty, GitHub creates a default on the first branch upload. Because it was a migrated repository, the first branch wasn't `main`.

We can always fix this "subsequent" to the migrated push, but another way is to first push an "empty commit" to `main` first before migration.

**Comment by HassanAkbar** [comment]
>Also /personal/rjs/7.40.1.dev0-root does not exist in svn - only /persona/rjs/7.40.1.dev0. Why is -root necessary here?

@ronaldtse By looking at this [reposurgeon code](https://gitlab.com/esr/reposurgeon/-/blob/master/surgeon/svnread.go#L3000), it feels like reposurgeon adds `-root` suffix to all tags which are not in [svn tag directory](https://svn.ietf.org/svn/tools/ietfdb/tags/).

According to the documentation, reposurgeon has the ability to rename/remove tags based on a regex so we can rename/remove all the tags with `-root` suffix or leave them as is. 

@rjsparks What do you suggest?

**Comment by ronaldtse** [comment]
@HassanAkbar based on that comment in reposurgeon, it seems that the branch names will "conflict" because reposurgeon had to create a separate Git branch for that particular for the SVN branch. Perhaps there is another `/personal/rjs/7.40.1.dev0` branch around?

**Comment by HassanAkbar** [comment]
@ronaldtse I have verified you can create a `branch` and a `tag` with same name in Github.

From what I understand from reposurgeon code, `-root` suffix is added to all the tags that are created from branches to differentiate them from actual tags in SVN that are in [svn tag directory](https://svn.ietf.org/svn/tools/ietfdb/tags/).
When creating tags from branches there are 2 possibilities :
1. The branch has no commits in that case the tag is created of the with the prefix `emptycommit-`.  For example: [emptycommit-19660](https://github.com/ietf-svn-conversion/ietfdb/releases/tag/emptycommit-19660).
2. The branch has some commits. In this case the tag is created by appending `-root` suffix at the end of branch name.

I am not sure which `branches` are converted to `tags`  by `reposurgeon`. (I can look into that if needed).

**Comment by rjsparks** [comment]
> @rjsparks Got it. We will remove mapping to n/a labels.

This doesn't look like it made it into the most recent run - should this be moved to its own ticket, or do we continue to track it in this thread.

**Comment by ronaldtse** [comment]
@rjsparks we are re-running the migrations and will ping you once done.

**Comment by ronaldtse** [comment]
@rjsparks I believe this task has been completed and the repository migrated. Is this task to be closed? Thanks.

**Comment by rjsparks** [comment]
I'm fine closing this issue, but I think we'll have a few other things to look into as we finish setting up the datatracker in github, I can open separate issues for them as they arise.

**Comment by ronaldtse** [comment]
Thanks @rjsparks , let's close this one and feel free to file new ones when issues arise.
