### ISSUE TITLE
Deliverable: New GitHub organisation and repository for the EMAILCORE Working Group correctly populated with migrated data from Trac.

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#10]

**Comment by ronaldtse** [comment]
Trac tickets available now at:
* `emailcore`: https://github.com/ietf-svn-conversion/emailcore

@rjsparks this repo is ready for review.

**Comment by rjsparks** [comment]
this looks correct

**Comment by ronaldtse** [comment]
@rjsparks can I confirm that the migration of this repository is completed? The link already redirects to the new organization. Thanks!

**Comment by rjsparks** [comment]
yes - this is complete

**Comment by ronaldtse** [comment]
Thanks! Closing.
