### ISSUE TITLE
Deliverable: New GitHub organisation and repository for the TSVWG Working Group correctly populated with migrated data from Trac.

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#11]

**Comment by ronaldtse** [comment]
Trac tickets and SVN data available now at:
* `tsvwg`: https://github.com/ietf-svn-conversion/tsvwg

@rjsparks this repo is ready for review.

**Comment by rjsparks** [comment]
this is ready (of course, all the ones marked ready will need a final run at a cutover flag-day)

**Comment by ronaldtse** [comment]
@rjsparks can I confirm that the migration of this repository is completed? The link already redirects to the new organization. Thanks!

**Comment by rjsparks** [comment]
Yes, this one is done.

**Comment by ronaldtse** [comment]
Thanks for the confirmation! Closing.
