### ISSUE TITLE
Review: setup repositories under ietf-svn-conversion organization

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#14]
We will need to setup the Git commit code and also the migrated issues to the repositories.

We must combine them in order to test the linkage between migrated commits and migrated issues. 

We need to do this before a formal review can happen by multiple reviewers.

**Comment by HassanAkbar** [comment]
@ronaldtse 
Though we divided `ietfdb` tickets into two repositories i.e. `ietfdb-datatracker` and `ietfdb-mailarchive`. But there is a single repository ietfdb in SVN and Github.
Will we migrate tickets of datatracker OR mailarchive to ietfdb repo ?
OR should we do something else here?

**Comment by ronaldtse** [comment]
ietfdb is the datatracker. So we migrate all mailarchive tickets to the mailarchive repo. 

We should just call the repos "ietfdb" and "mailarchive" rather than "ietfdb-datatracker" and "ietf-mailarchive".

**Comment by ronaldtse** [comment]
@rjsparks can we confirm that mailarchive tickets go to the "mailarch" repo? (https://github.com/ietf-ribose/mailarch)

**Comment by rjsparks** [comment]
> @rjsparks can we confirm that mailarchive tickets go to the "mailarch" repo? (https://github.com/ietf-ribose/mailarch)

That is correct

**Comment by ronaldtse** [comment]
Thanks! Got tripped up in the names...

**Comment by ronaldtse** [comment]
> Though we divided `ietfdb` tickets into two repositories i.e. `ietfdb-datatracker` and `ietfdb-mailarchive`. But there is a single repository ietfdb in SVN and Github.

@HassanAkbar

* `ietfdb` repo and `ietfdb` tickets (the non-`mailarchive` tickets) => https://github.com/ietf-ribose/ietfdb
* `mailarch` repo and `mailarchive` tickets => https://github.com/ietf-ribose/mailarch

**Comment by HassanAkbar** [comment]
@ronaldtse  I have migrated the code and tickets in these repos.
There are available for review.
I am working on the open issues:

bibxml -> https://github.com/ietf-svn-conversion/bibxml-final
mailreplay -> https://github.com/ietf-svn-conversion/mailreplay-final
postconfirm -> https://github.com/ietf-svn-conversion/postconfirm-final
postfind -> https://github.com/ietf-svn-conversion/postfind-final
tsvwg -> https://github.com/ietf-svn-conversion/tsvwg-final
emailcore -> https://github.com/ietf-svn-conversion/emailcore-final
dmarc -> https://github.com/ietf-svn-conversion/dmarc-final
mailarchive -> https://github.com/ietf-svn-conversion/mailarch-final
ietfdb (datatracker) -> https://github.com/ietf-svn-conversion/ietfdb-final

**Comment by ronaldtse** [comment]
@HassanAkbar thanks, we are still missing these repos:
* vocabulary_design_team_2013_2017
* xml2rfc-website
* xml2rfc-bibxml
* xml2rfc

**Comment by HassanAkbar** [comment]
@ronaldtse Here are the missing repos.

vocabulary_design_team_2013_2017 -> https://github.com/ietf-svn-conversion/vocabulary_design_team_2013_2017-final
xml2rfc-website -> https://github.com/ietf-svn-conversion/xml2rfc-website-final
xml2rfc-bibxml ->  https://github.com/ietf-svn-conversion/xml2rfc-bibxml-final
xml2rfc -> https://github.com/ietf-svn-conversion/xml2rfc-final

**Comment by ronaldtse** [comment]
@HassanAkbar thanks, but the https://github.com/ietf-svn-conversion/vocabulary_design_team_2013_2017-final repo has the wrong contents. Can you help fix?

**Comment by HassanAkbar** [comment]
@ronaldtse https://github.com/ietf-svn-conversion/vocabulary_design_team_2013_2017-final has been fixed.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar!

I've renamed them, and the final list is:
* `mailreplay`: https://github.com/ietf-svn-conversion/mailreplay
* `postconfirm`: https://github.com/ietf-svn-conversion/postconfirm
* `postfind`: https://github.com/ietf-svn-conversion/postfind
* `tsvwg`: https://github.com/ietf-svn-conversion/tsvwg
* `emailcore`: https://github.com/ietf-svn-conversion/emailcore
* `dmarc`: https://github.com/ietf-svn-conversion/dmarc
* `mailarchive`: https://github.com/ietf-svn-conversion/mailarch
* `ietfdb` (datatracker): https://github.com/ietf-svn-conversion/ietfdb
* `vocabulary_design_team_2013_2017`: https://github.com/ietf-svn-conversion/vocabulary_design_team_2013_2017
* `xml2rfc-website`: https://github.com/ietf-svn-conversion/xml2rfc-website
* `xml2rfc-bibxml`: https://github.com/ietf-svn-conversion/xml2rfc-bibxml
* `xml2rfc`: https://github.com/ietf-svn-conversion/xml2rfc

**Comment by rjsparks** [comment]
Will it be hard to have the result of the datatracker extraction be named `datatracker` rather than `ietfdb`?

**Comment by ronaldtse** [comment]
> Will it be hard to have the result of the datatracker extraction be named datatracker rather than ietfdb?

Not difficult, we will create such a task. In fact, we can just rename the current migrated repo for the purpose of the review.

**Comment by rjsparks** [comment]
The vocabulary_design_team_2013_2017 repository code looks good, but the issues aren't right yet - there are many issues there that are xml2rfc issues, not design team issues - I think the filter right now may have simply been the component (v3 vocabulary) - the selection will need to be more nuanced.

**Comment by rjsparks** [comment]
Could we please bring @kesara into this project?

**Comment by ronaldtse** [comment]
@rjsparks, just invited @kesara to the project.

**Comment by rjsparks** [comment]
For vocabulary_design_team_2013_2107 - my current thoughts are that we do not migrate any trac issues into it at all, and have these go into the xml2rfc repository. I'm checking with members of that design team to see if they think that's right as well - lets give them a day or so to respond.

**Comment by rjsparks** [comment]
I spotted an a potential global issue - all of the closed issues appear to be closed at the time the migration was run rather than when the issues were actually closed? I noticed this first in the mailarch repo, and confirmed it in the emailcore repo. Please help check the rest.

**Comment by rjsparks** [comment]
> For vocabulary_design_team_2013_2107 - my current thoughts are that we do not migrate any trac issues into it at all, and have these go into the xml2rfc repository. I'm checking with members of that design team to see if they think that's right as well - lets give them a day or so to respond.

I've received enough responses to feel comfortable that this is what we should do.

**Comment by ronaldtse** [comment]
Closing this since there are no further tasks entailed here.
