### ISSUE TITLE
Confirmation of GitHub user to use for migration

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#16]
Since we are going to prepare a full migration for review, we will need to use a GitHub user to run it with.

What user should we use for this purpose?

(cc: @rjsparks )

**Comment by rjsparks** [comment]
My first thoughts on this are at the start of https://github.com/ietf-ribose/svn-github-convert/issues/18#issuecomment-953006848

> So then the final migration should be done by an identity that makes it very clear what happened. An account created for just this purpose with a name of 'ietfsvnmigration' or something that conveys the message but is shorter.

I'm willing to bikeshed a bit on what a good name for this would be since it will be strongly present in the end result.

Lets also discuss the lifecycle of the user - which of us will create it? I assume we would hold the credentials for it when we're done?

**Comment by larseggert** [comment]
"Tools Team"?

**Comment by jennifer-richards** [comment]
"ietf-migration" or "ietf-trac"? Something that sounds automated.

Whatever the name, it'd be good to arrange for the window that opens on mouse-over to give a clear indication of the account's nature. (I think that's just a matter of setting the real name of the user)

**Comment by ronaldtse** [comment]
> Lets also discuss the lifecycle of the user - which of us will create it? I assume we would hold the credentials for it when we're done?

Potentially @rjsparks could create the user, provide us with sufficient credentials (GitHub's Personal Access Token) to run the migration, and once everything is done, revoke that token?

**Comment by HassanAkbar** [comment]
@rjsparks Have you guys finalized any Github user for migration purposes yet?

**Comment by rjsparks** [comment]
Yes, and thanks for the nudge. I've created ietf-svn-bot and will send Ron (I don't think I have email for @HassanAkbar) an api key.

**Comment by ronaldtse** [comment]
@HassanAkbar just to clarify the new GitHub user is called "ietf-svn-bot", and the token is now available in this organization's repositories as `IETF_SVN_BOT_PAT_TOKEN`. Thanks!

**Comment by ronaldtse** [comment]
Thank you @rjsparks !
