### ISSUE TITLE
Deliverable: New GitHub repository for Mailarchive correctly populated with migrated data from Trac and Subversion.

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#2]

**Comment by ronaldtse** [comment]
Trac tickets and SVN data available now at:
* `mailarchive`: https://github.com/ietf-svn-conversion/mailarch

@rjsparks this repo is ready for review.

**Comment by rjsparks** [comment]
This one has issues. There are thousands of closed issues that aren't things that should have landed in this repo (they appear as things like `Not available in trac 1 closed`.

All of the closed issues appear to be closed on the same time - basically when the conversion was run (and I see this affects the other repositories too, so this is a global issue).

**Comment by ronaldtse** [comment]
@rjsparks the closed tickets are used to maintain the ID to ID mapping between Trac tickets and GitHub issues, as previously discussed. 

If we don't want the one to one ID mapping, it's just an option to switch off in Tractive.

**Comment by rjsparks** [comment]
> @rjsparks the closed tickets are used to maintain the ID to ID mapping between Trac tickets and GitHub issues, as previously discussed.
> 
> If we don't want the one to one ID mapping, it's just an option to switch off in Tractive.

The one-one mapping is valuable - we'll deal with cleaning the not availbles after.

Just to make sure it wasn't lost - note the concern about all closed tickets (not just the ones that say "not available")  having the same time instead of the time they were actually closed.

**Comment by ronaldtse** [comment]
Got it, so we will retain the one-to-one mapping -- but please feel free to suggest any changes to those placeholder messages to make them clearer.

Sorry for missing a reply on the "closed ticket time" part. Actually we wanted to do some research about it before getting back to you on it.

In particular, it **might** be possible that GitHub can accept the original closure time, we just need to try.

The relevant code in Tractive is (courtesy of @HassanAkbar ):

https://github.com/ietf-ribose/tractive/blob/212ea5b5649376a3b19e01004d054912a996e099/lib/tractive/migrator/engine.rb#L106

**Comment by HassanAkbar** [comment]
I have verified that the original time of closure can be added to the tickets.
I will update the tractive code to include the actual `closed time` for tickets.

@rjsparks For the closed tickets added to maintain ID to ID mapping between Trac tickets and GitHub issues, do we want to add any specific `closed time` (that might help in filtering such issues)?

**Comment by rjsparks** [comment]
last unix epoch-ish perhaps?

**Comment by rjsparks** [comment]
> please feel free to suggest any changes to those placeholder messages to make them clearer.
How about "Placeholder issue #{ticket_id} created to align github issue and trac ticket numbers during migration."

And after the migration's done - what would the consequence of deleting those things be?

**Comment by ronaldtse** [comment]
@rjsparks GitHub doesn't allow "deletion" of issues, only "closure".

**Comment by rjsparks** [comment]
![image](https://user-images.githubusercontent.com/10996692/144619311-90512cfb-6d8d-4096-b931-a76be32298df.png)

**Comment by ronaldtse** [comment]
@rjsparks wow that's a (not so new) feature I never knew about! Thanks...

Since 2018-11-08: https://hub.packtpub.com/github-now-allows-repository-owners-to-delete-an-issue-curse-or-a-boon/

**Comment by ronaldtse** [comment]
Here's my experiment.

1. I created 3 issues

<img width="957" alt="Screenshot 2021-12-03 at 10 46 09 PM" src="https://user-images.githubusercontent.com/11865/144621848-7541ccf4-a15a-4c59-8f1c-79b754e20ce4.png">

2. Deleted 1

<img width="965" alt="Screenshot 2021-12-03 at 10 46 24 PM" src="https://user-images.githubusercontent.com/11865/144621879-e4d8a88c-ef9c-4dd7-bd5e-1bcfba12d376.png">

3. Created a new issue, which got assigned as 4, which is correct.

<img width="949" alt="Screenshot 2021-12-03 at 10 47 32 PM" src="https://user-images.githubusercontent.com/11865/144622053-b959370f-1217-4def-8a72-757c1f6e0686.png">

4. Deleted 3

5. Created new issue, which is assigned 5, correct.

6. See if I can still refer back to the deleted issues 1 and 3, which I couldn't, and that is correct.

<img width="612" alt="Screenshot 2021-12-03 at 10 49 01 PM" src="https://user-images.githubusercontent.com/11865/144622284-fd4fe6a1-9723-43de-a640-57cf4b46d0e7.png">

So I don't think there would be any particular drawbacks.

**Comment by HassanAkbar** [comment]
@ronaldtse this is also done.

**Comment by ronaldtse** [comment]
Thanks!
