### ISSUE TITLE
Placeholder GitHub Issues can be deleted (according to configuration)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#20]
GitHub now provides an Issue "delete" button that we can use to remove the placeholder Issues we create for sequential numbering. (e.g. if the ticket was deleted from Trac prior to import).

(Since 2018-11-08: https://hub.packtpub.com/github-now-allows-repository-owners-to-delete-an-issue-curse-or-a-boon/)

By deleting the placeholder issues we prevent confusion by users who wonder why an issue was empty.

We should make this a default option to delete the placeholder issue once it is created.

This was my experiment on GitHub that worked.

1. I created 3 issues

<img width="957" alt="Screenshot 2021-12-03 at 10 46 09 PM" src="https://user-images.githubusercontent.com/11865/144621848-7541ccf4-a15a-4c59-8f1c-79b754e20ce4.png">

2. Deleted 1

<img width="965" alt="Screenshot 2021-12-03 at 10 46 24 PM" src="https://user-images.githubusercontent.com/11865/144621879-e4d8a88c-ef9c-4dd7-bd5e-1bcfba12d376.png">

3. Created a new issue, which got assigned as 4, which is correct.

<img width="949" alt="Screenshot 2021-12-03 at 10 47 32 PM" src="https://user-images.githubusercontent.com/11865/144622053-b959370f-1217-4def-8a72-757c1f6e0686.png">

4. Deleted 3

5. Created new issue, which is assigned 5, correct.

6. See if I can still refer back to the deleted issues 1 and 3, which I couldn't, and that is correct.

<img width="612" alt="Screenshot 2021-12-03 at 10 49 01 PM" src="https://user-images.githubusercontent.com/11865/144622284-fd4fe6a1-9723-43de-a640-57cf4b46d0e7.png">

So I don't think there would be any particular drawbacks.

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/github-migration-project/issues/2#issuecomment-985580933_

**Comment by HassanAkbar** [comment]
@ronaldtse I didn’t find any endpoint in the `Github REST API` to delete the issues but there is an endpoint in [`Github GraphQL API`](https://docs.github.com/en/graphql/reference/mutations#deleteissue) but it also will only delete one issue at a time.

We can loop through all issues and use this API.

**Comment by ronaldtse** [comment]
@HassanAkbar thank you for the investigation. Let's use the GitHub GraphQL API to delete issues one at a time, there might be traffic limits that we need to account for.
