### ISSUE TITLE
Converting owner to a label is probably the wrong thing to do for xml2rfc, datatracker, and mailarchive

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#24]
These projects have used 'owner' with inconsistent semantics, and while the current set of information shouldn't be lost, having it move to labels is turning out to be the wrong choice.

For the datatracker, at least, it is creating a large number of labels that will be attractive nuisances going forward.

Instead, would it be hard to map them into the text commit before the initial `| by <foo>`? (I seem to recall that's what we were doing initially, and we asked to have owner pulled into labels, and if so, I apologize for the change in direction)

**Comment by HassanAkbar** [comment]
@rjsparks Yes we can make that change.
Do we need to change it for all or only the 3 mentioned repositories?

**Comment by rjsparks** [comment]
Just these three is sufficient
