### ISSUE TITLE
keywords are lost

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#25]
See, for example, https://trac.ietf.org/trac/ietfdb/ticket/3429 and note the keyword of 'sprint'.

Compare that to https://github.com/ietf-svn-conversion/datatracker/issues/3429 where the string 'sprint' does not occur anywhere.

Given that the trac allowed freeform entry here, I don't think these should get mapped to labels, but we need to keep them somewhere, and adding them to the text in the initial message in the area before `| by <foo>` would be sufficient I think.

See https://trac.ietf.org/trac/ietfdb/query?keywords=!&component=!MailArchive%3A+ArchiveContents&component=!MailArchive%3A+User+Interface&group=priority&max=9999&col=id&col=keywords&report=35&desc=1&order=id for an idea of what lies in the field.

Brainstorming:

I suggest that if possible, we split the contents of the field on comma and for each element in the split, add `keyword_<element>`. 

So for https://trac.ietf.org/trac/ietfdb/ticket/1295, we would add `keyword_tags, keyword_check-box, keyword_sprint, keyword_easy`.

Some of the freetext has spaces in it, so I suggest mapping spaces to underscores, so that for https://trac.ietf.org/trac/ietfdb/ticket/2470 we would add `keyword_html_santitize_css_style`.

I'm open to other suggestions on how to not lose these.

**Comment by HassanAkbar** [comment]
@rjsparks 
I don't have access to https://trac.ietf.org/.
I tried creating an account but got an error: `Our apologies, it looks like there was an issue creating your account`

Can you guide me on how I can login into https://trac.ietf.org/ or paste the content of the above links here ?

**Comment by rjsparks** [comment]
I'll contact you by email to work out the datatracker account setup. In the meantime some previews:

**Comment by rjsparks** [comment]
![image](https://user-images.githubusercontent.com/10996692/149633042-9418d1f6-888c-421d-8b1e-c29f16880957.png)

**Comment by rjsparks** [comment]
![image](https://user-images.githubusercontent.com/10996692/149633071-134f0ac3-08df-4cde-ae3c-037898721311.png)
