### ISSUE TITLE
conversion doesn't preserve permission bits

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#27]
In the xml2rfc conversion there were several scripts that had their executable bit set as a property in svn, but that didn't translate into the right properties in git/github.

If it's fast to add, it would be extremely helpful to preserve that information for the datatracker and mailarchive conversions.

For example:

```
rjsparks@undex bin % pwd
/Users/rjsparks/ietf/datatracker/trunk/ietf/bin
rjsparks@undex bin % svn proplist send-scheduled-mail
Properties on 'send-scheduled-mail':
  svn:executable
```

There are a lot of these in trunk (and probably many more in branches), so fixing them up manually would be quite a chore.

```
rjsparks@undex trunk % svn proplist -R . | grep -B3 svn:executable | grep '^Prop' | wc
     168     504    8846
```

**Comment by ronaldtse** [comment]
@rjsparks we'll have to investigate why that happens, that's strange. I wasn't aware that the process would drop the executable bit.

From http://www.catb.org/~esr/reposurgeon/repository-editing.html#CVS it says:
> The svn:executable and svn:special properties are translated into permission settings in the input stream; svn:executable becomes 100755 and svn:special becomes 120000 (indicating a symlink; the blob contents will be the path to which the symlink should resolve).

@HassanAkbar can you help check why this happens? Thanks.

**Comment by HassanAkbar** [comment]
I've looked into this, reposurgeon is adding execute permission to the files. I looked into the [xml2rfc repo](https://github.com/ietf-tools/xml2rfc) and found that the permissions were changed after the migration in [this PR](https://github.com/ietf-tools/xml2rfc/commit/895a85d9d40ea8c6df376533c67dd559d5376d6e).

<img width="1440" alt="Screenshot 2022-02-16 at 5 28 10 PM" src="https://user-images.githubusercontent.com/5301572/154264719-5d51704f-6b80-4116-8d24-fdec4d4c3b2c.png">

**Comment by ronaldtse** [comment]
Thank you for the investigation @HassanAkbar . I think we can close this task now?

**Comment by HassanAkbar** [comment]
> Thank you for the investigation @HassanAkbar . I think we can close this task now?

Yes, I think it can be closed.
