### ISSUE TITLE
xml2rfc ticket attachments are broken

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#28]
(discovered by @kesara)
See https://github.com/ietf-tools/xml2rfc/issues/624#issuecomment-1032282719
The link to the provided attachment 404s. The repository exists, but the links don't line up?

**Comment by rjsparks** [comment]
@HassanAkbar - was there an updated attachments repository for xml2rfc that needs to be put in place?

**Comment by HassanAkbar** [comment]
@rjsparks There are currently 2 issues for this file.
1. The URL is not pointing to the correct folder. (A mistake on my part while running the migration)
2. The image provided above does not exist even in the correct folder.

For the first issue we can rename the folder in the [`svntrac-converted-attachments`](https://github.com/ietf-tools/svntrac-converted-attachments) repo but for that I would need write access to the repo.

For the second issue, I think the attachment you provided above is deleted in trac because it is not even in the latest dump which was 5 hours ago.  To confirm this I would need access to [`xml2rfc trac instance`](https://trac.ietf.org/trac/xml2rfc/) or can you verify that the file is attached to the given issue in trac?

**Comment by rjsparks** [comment]
>  I would need write access to the repo.

Invite sent.

> would need access to [xml2rfc trac instance](https://trac.ietf.org/trac/xml2rfc/)

You already _have_ access. Unlike ietfdb, you can browse this svn repo completely without logging in. (And for ietfdb, all you need to do is create and use [datatracker credentials](https://datatracker.ietf.org/accounts/create/).

The [relevant ticket is here](https://trac.ietf.org/trac/xml2rfc/ticket/624), and you are correct - its attachment is missing.

Fwiw [ticket 707](https://trac.ietf.org/trac/xml2rfc/ticket/707), the most recent with attachments, still has its.

But from some point later than 624 and before, ticket attachements are missing in trac.

If I am able to restore those, would you be able to connect them to the right places?

**Comment by HassanAkbar** [comment]
Issue 1 is fixed now. Every file that is present on trac is now accessible in GitHub.

> If I am able to restore those, would you be able to connect them to the right places?

Yes If the files are available through rsync then I put them in the attachments repo.

**Comment by rjsparks** [comment]
[ticket 584](https://trac.ietf.org/trac/xml2rfc/ticket/584) and earlier (end of 2020) seem to have their attachments.

[ticket 641](https://trac.ietf.org/trac/xml2rfc/ticket/641) and after (May-June 2021) seem to have their attachments.

There was significant trac reconfiguration of the xml2rfc instance on 14 May 2021. 

For now, we will have to assume the attachments in that period are gone. I'll look to see if we have deep-backups that we could ask to access, but I expect that to be unlikely.

**Comment by rjsparks** [comment]
I've confirmed that there are no backups to inspect. If these attachments are needed in the future, the will have to be reconstructed.

How easy is it to scan (programatically, not by hand) for tickets with attachments that 404 - we could add a comment to those indicating that the attachment breakage is a known problem perhaps...

**Comment by HassanAkbar** [comment]
> How easy is it to scan (programatically, not by hand) for tickets with attachments that 404

It shouldn't be that complex. I can write a script to pull all such tickets.

**Comment by rjsparks** [comment]
The same brokenness happened to the source trac repo in ietfdb - missing attachments for the same time range.
If the script that finds all such tickets for the xml2rfc repository works (and especially if it can then add a comment that we know the attachments are broken), please also run it on datatracker and mailarch.

**Comment by ronaldtse** [comment]
The script should apply to those repositories as well. @HassanAkbar can you let @rjsparks know once you have results for those? Thanks.

**Comment by HassanAkbar** [comment]
These are the tickets with invalid URLs:
- `xml2rfc:`
  - 590
  - 592
  - 596
  - 512
  - 608
  - 603
  - 615
  - 620
  - 624
  - 619
  - 622
- `Datatracker/Mailarch:`
  - 3178
  - 3172
  - 3211
  - 3223
  - 3212
  - 3135
  - 3263
  - 3274
  - 3277
  
@rjsparks What do you suggest should I add a comment or a label to these tickets?
What would be an appropriate text for these comments/labels?

**Comment by rjsparks** [comment]
A comment please.

If this is something you can easily script, add

"The attachments for these issues were lost in trac before the transition to github, and cannot be recovered. If the issue is still relevant, and the attachments can be reconstructed, please add them as new comments."

Otherwise, we can find someone to do that manually since the number of affected issues is relatively low.

**Comment by HassanAkbar** [comment]
I ran the script and added the comment in the above-mentioned issues.
@rjsparks can you verify?

**Comment by rjsparks** [comment]
looks good

**Comment by rjsparks** [comment]
heh - it looks like some updates were made by this last bot to things in ietf-svn-conversion/datatracker-old and /xml2rfc-old. Can these repos be taken down?

**Comment by HassanAkbar** [comment]
> heh - it looks like some updates were made by this last bot to things in ietf-svn-conversion/datatracker-old and /xml2rfc-old. Can these repos be taken down?

Yes, I actually tested the script on these repos.
I will delete them now.
