### ISSUE TITLE
At least one attachment for ietfb->datatracker that _was_ in trac didn't make it through the transition

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#29]
See https://github.com/ietf-tools/datatracker/issues/3558
The attachment link in the second comment 404s.
In the trac view of that ticket (https://trac.ietf.org/trac/ietfdb/ticket/3558), the link to the attachment (https://trac.ietf.org/trac/ietfdb/attachment/ticket/3558/no-double-degfm.patch) does not 404.

Note that I manually reattached the contents of that attachment already at comment 4.

Please look to see why the attachment link in comment 2 didn't work, and if we have other issues with a similar problem?

**Comment by ronaldtse** [comment]
Thanks for reporting @rjsparks , this might be a bug...

**Comment by HassanAkbar** [comment]
The [attachments](https://github.com/ietf-tools/svntrac-converted-attachments) repo was outdated. I have updated it so this issue should be resolved now.

**Comment by rjsparks** [comment]
thanks - this looks good to me.

**Comment by ronaldtse** [comment]
Thanks!
