### ISSUE TITLE
The converted wiki was broken by transfering the project

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#30]
This wiki has many internal links to the staging repository - such as https://github.com/ietf-svn-conversion/datatracker/wiki/NativeSetup

See https://github.com/ietf-tools/datatracker/wiki/SprintCoderSetup for an example.

Can this be easily repaired?

**Comment by HassanAkbar** [comment]
I think we need to change the svn command like below to Git command by defining a mapping:
```
$ svn co http://svn.tools.ietf.org/svn/tools/ietfdb/personal/<<yourname>>/<<version>>
```
But this will require some time because for this we will first need to extract all the `svn commands` and `URLs` and then we will have to generate a mapping for them. Once we have the mapping we can write a script to update the references.

@rjsparks Am I missing something here?

**Comment by rjsparks** [comment]
You're looking at a different problem, and one that I'm not wanting to try solve with scripting.  I'm not pointing to remaining svn.tools.ietf.org or even svn.ietf.org links (or even the trac links).

I'm pointing to the internal links within the wiki itself. Look again at the URL in the first comment and note that it still points to the now non-existant ietf-svn-conversion repository.

These only work because of github's automatic redirects. They will stop working (or will start working differently in a _very_ surprising way) if something ever gets created again at github.com/ietf-svn-conversion/datatracker.

**Comment by rjsparks** [comment]
To be a little more specific: Go to https://github.com/ietf-tools/datatracker/wiki/SprintCoderSetup. Hover over the link the first paragraph of the introduction (or view source). Note that the link is to https://github.com/ietf-svn-conversion/datatracker/wiki/NativeSetup and not to https://github.com/ietf-tools/datatracker/wiki/NativeSetup.

**Comment by HassanAkbar** [comment]
> https://github.com/ietf-tools/datatracker/wiki/SprintCoderSetup

Sorry, my bad. 
Got it now. Yes, these are staging repo links they are redirected to the new repo.
Yes, we can replace these links.

**Comment by HassanAkbar** [comment]
@rjsparks I have written a script that will transform all the URLs to point to the new repo. This will add a new commit in wiki history.

Just for confirmation should I use `ietf-svn-bot` for this commit?
Can you also provide an email for this user?
To make a commit from a user, Github requires the username and email of that account.

**Comment by rjsparks** [comment]
Address sent by email

**Comment by HassanAkbar** [comment]
@ronaldtse @rjsparks I need a user with access to the Datatracker repo to update the wikis.

Currently `IETF_RIBOSE_CI_SSH_PRIVATE` key is available in the [workflow](https://github.com/ietf-ribose/svn-github-convert/blob/main/.github/workflows/update_wikis.yml) but this does not have access to the `Datatracker` repo. Can you add another key with access to the repo?

**Comment by rjsparks** [comment]
I'm on a skinny device at the moment - it will be later in the day before I can build such a key.
I wonder if doing the work on a fork of the wiki repo and having the svn bot make a pr (which I can do) might work?

**Comment by HassanAkbar** [comment]
> https://github.com/ietf-tools/datatracker/wiki/SprintCoderSetup

Actually, forking wiki repo is not possible. 
Take your time, we can run the script when the key is added.

**Comment by ronaldtse** [comment]
@HassanAkbar we can git clone the wiki from the repo, push it manually to a new GitHub repo, do the work there, and then git push it back to the original wiki. Would that work?

**Comment by HassanAkbar** [comment]
> @HassanAkbar we can git clone the wiki from the repo, push it manually to a new GitHub repo, do the work there, and then git push it back to the original wiki. Would that work?

@ronaldtse I am trying this option already.
If it goes well then we will let you know.

**Comment by HassanAkbar** [comment]
@rjsparks @ronaldtse we can't open a PR on a wiki repo.
We can use [squash changes in one commit & cherry pick](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) it.

**Comment by rjsparks** [comment]
I found a way to do this quickly with command-line git, so I just made the changes as me. Sorry for the extra work that went into this. We can close this issue without further action.

For what it's worth, this is what I did:
```
$ git clone git@github.com:ietf-tools/datatracker.wiki.git
$ cd datatracker.wiki
$ sed -i '.old' 's/ietf-svn-conversion/ietf-tools/g' *md
$ rm *old
$ git commit -a -m 'Change ietf-svn-conversion to ietf-tools globally.'
$ git push origin master
```
