### ISSUE TITLE
Create mapping for externally-referenced Trac pages to new GitHub address

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#31]
We've manually combed through Google to obtain these links. Given that we do not have full access to the data on the www.ietf.org or datatracker.ietf.org, it is hard for us to further verify if any links are missing.

These are the queries we used:
* `"trac.ietf.org"` and `"trac.tools.ietf.org"`
* with site specified as `site:www.ietf.org` and `site:rfc-editor.org`

The next step is to find out:
1. whether these links are still active;
2. If so, find out if they have a corresponding page in GitHub.

Some links are probably not mappable, e.g.:
* `https://trac.tools.ietf.org/tools/ietfdb/browser/trunk/ietf/meeting/placement.py?rev=12923`

OLD:
[20220316-ietf-links-to-trac-wo-datatracker.txt](https://github.com/ietf-ribose/github-migration-project/files/8265581/20220316-ietf-links-to-trac-wo-datatracker.txt)

UPDATED: (includes Internet-Draft links now)
[20220316-ietf-links-to-trac-v2.txt](https://github.com/ietf-ribose/github-migration-project/files/8266938/20220316-ietf-links-to-trac-v2.txt)

**Comment by ronaldtse** [comment]
@rjsparks for links that exist on Datatracker, could you help either provide the data, or find a way to provide us with the links so we can map?

**Comment by ronaldtse** [comment]
Updated file now includes links from Internet-Drafts.

**Comment by HassanAkbar** [comment]
I have added the new URL (wherever possible) and comments in [Trac links mapping.txt](https://github.com/ietf-ribose/github-migration-project/files/8302035/Trac.links.mapping.txt).

Let me know if you need anything else.

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar ! This should be comprehensive enough for @rjsparks to determine next steps.

**Comment by rjsparks** [comment]
one question on the scan for drafts - were you only looking for `<a href=` or did your check also look into the raw text?
(Don't do more if you only looked for hrefs - I just want to know what the current pass covers).

**Comment by ronaldtse** [comment]
@rjsparks it was a search through all href and text, so it should be very comprehensive if not fully complete.

The disclaimer is that we relied on Google indexed pages, so we have no way of verifying whether the set is complete. It would be much easier on your side to grep for the links as you have full data.

**Comment by ronaldtse** [comment]
@rjsparks similar to #32 there are several Trac projects (issues and wikis) that were not migrated and hence do not have mappings. Not sure what you wish to do with them. If there's anything else we can help with, let us know.

**Comment by rjsparks** [comment]
I think this is also sufficient.

**Comment by ronaldtse** [comment]
Thanks @rjsparks !
