### ISSUE TITLE
Create mapping for externally-referenced SVN pages to new GitHub address

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#32]
We've manually combed through Google to obtain these links. Given that we do not have full access to the data on the www.ietf.org or datatracker.ietf.org, it is hard for us to further verify if any links are missing.

These are the queries we used:
* `"svn.ietf.org"` and `"svn.tools.ietf.org"`
* with site specified as `site:www.ietf.org` and `site:rfc-editor.org`

The next step is to find out:
1. whether these links are still active;
2. If so, find out if they have a corresponding page in GitHub.

Not sure if all links are mappable, e.g.:
* `https://svn.tools.ietf.org/svn/wg/dnsop/doclist.html`

OLD:
[20220316-ietf-links-to-svn.txt](https://github.com/ietf-ribose/github-migration-project/files/8265753/20220316-ietf-links-to-svn.txt)

UPDATED (now includes links from Internet-Drafts):
[20220316-ietf-links-to-svn-v2.txt](https://github.com/ietf-ribose/github-migration-project/files/8266931/20220316-ietf-links-to-svn-v2.txt)

**Comment by ronaldtse** [comment]
@rjsparks for links that exist on Datatracker, could you help either provide the data, or find a way to provide us with the links so we can map?

**Comment by rjsparks** [comment]
As noted at #12, you don't need to comb the datatracker.

**Comment by ronaldtse** [comment]
Sorry, I meant the SVN/Trac links that exist in the Internet-Drafts corpus -- is this something that we still should complete?

**Comment by ronaldtse** [comment]
I've added the links from Internet-Drafts now.

**Comment by HassanAkbar** [comment]
I have added the new URL (wherever possible) and comments in [SVN links mapping.txt](https://github.com/ietf-ribose/github-migration-project/files/8287313/SVN.links.mapping.txt)


Let me know if you need anything else.

**Comment by ronaldtse** [comment]
@HassanAkbar I can't load the attached file, it led to a 404. Can you re-upload it? Thanks.

**Comment by HassanAkbar** [comment]
> @HassanAkbar I can't load the attached file, it led to a 404. Can you re-upload it? Thanks.

Uploaded again. [SVN links mapping.txt](https://github.com/ietf-ribose/github-migration-project/files/8311402/SVN.links.mapping.txt)

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar !
- One issue: http://svn.tools.ietf.org/svn/src/ghostlinkd has been migrated into https://github.com/ietf-ribose/ghostlinkd (@rjsparks has not migrated it to ietf-tools yet)

@rjsparks could you look at the mapping and let us know what you think?

**Comment by rjsparks** [comment]
I am _surprised_ that ghostlinkd hasn't been moved. I'll double-check what happened and move it.

The mapping file is likely sufficient. I need to distill it into a set of generic patterns for building redirects - I think very few of the instances you've found will require an instance specific rule.

**Comment by rjsparks** [comment]
>One issue: http://svn.tools.ietf.org/svn/src/ghostlinkd has been migrated into https://github.com/ietf-ribose/ghostlinkd (@rjsparks has not migrated it to ietf-tools yet)

You mean https://github.com/ietf-svn-conversion/ghostlinkd/

**Comment by rjsparks** [comment]
ghostlinkd is moved. That leaves 3 things in ietf-svn-conversion. Those should probably go away?

**Comment by ronaldtse** [comment]
> You mean https://github.com/ietf-svn-conversion/ghostlinkd/

Right, sorry!

> That leaves 3 things in ietf-svn-conversion. Those should probably go away?

Indeed. Since datatracker has been moved we can remove it. The two remaining are just testing artefacts. We'll get them removed. Thanks!
