### ISSUE TITLE
Clean up unneeded orgs and repos

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#33]
I think these organizations are not necessary anymore? (Not sure they ever got used - the real places are different.
https://github.com/ietf-tsvwg
https://github.com/ietf-emailcore
https://github.com/ietf-dmarc
It looks to me like Ribose created them (looking at the billing email address in settings).
The real places those went were created by the secretariat and have org names that look like ietf-wg-acronym

If there's not some reason to keep them, can they be deleted?

Are there other intermediate artifacts that should go away?

**Comment by ronaldtse** [comment]
@rjsparks yes! They were originally intended to deliver those email lists in, but they were never used. @JayDaley and your accounts are marked as owners. The easy way for us is just to exit them so you can keep them, alternatively we can delete them once and for all. What do you think?

**Comment by rjsparks** [comment]
I think it's fine to just delete them.

**Comment by ronaldtse** [comment]
@rjsparks they have been deleted now. Thanks!
