### ISSUE TITLE
Deliverable: New GitHub repository for xml2rfc correctly populated with migrated data from Trac and Subversion.

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#6]

**Comment by ronaldtse** [comment]
Trac tickets and SVN data available now at:
* `xml2rfc`: https://github.com/ietf-svn-conversion/xml2rfc

@rjsparks this repo is ready for review.

**Comment by kesara** [comment]
I found several issues with "Not available in trac" that has not being migrated properly: https://github.com/ietf-svn-conversion/xml2rfc/search?p=2&q=%22Not+available+in+trac%22&type=issues
Looks like all the issues below #640 are not migrated properly.

**Comment by HassanAkbar** [comment]
> I found several issues with "Not available in trac" that has not being migrated properly ietf-ribose/tractive#65

@kesara This will be fixed by https://github.com/ietf-ribose/tractive/issues/65
