### ISSUE TITLE
Deliverable: New GitHub repository for the xml2rfc web service correctly populated with migrated data from Trac and Subversion.

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#7]

**Comment by ronaldtse** [comment]
Trac tickets and SVN data available now at:
* `xml2rfc-website`: https://github.com/ietf-svn-conversion/xml2rfc-website

@rjsparks this repo is ready for review.

**Comment by rjsparks** [comment]
this repo is ready

**Comment by ronaldtse** [comment]
@rjsparks can I confirm that the migration of this repository is completed? The link already redirects to the new organization. Thanks!

**Comment by rjsparks** [comment]
yes, this is complete

**Comment by ronaldtse** [comment]
Thanks! Closing.
