### ISSUE TITLE
Deliverable: New GitHub organisation and repository for the DMARC Working Group correctly populated with migrated data from Trac.

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-migration-project#9]

**Comment by ronaldtse** [comment]
Trac tickets available now at:
* `dmarc`: https://github.com/ietf-svn-conversion/dmarc

@rjsparks this repo is ready for review.

**Comment by rjsparks** [comment]
this looks right

**Comment by rjsparks** [comment]
This repo has been handed off, and this issue could be closed?

**Comment by ronaldtse** [comment]
Thanks @rjsparks !
